baseURL: "https://ErvinZzz.github.io/" 
title: Lechen Zhang
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Home
          url: /
          weight: 1
        - name: CV
          url: cv.pdf
          weight: 2
        - name: Papers
          url: /papers/
          weight: 3
        - name: Projects
          url: /projects/
          weight: 4
        - name: Design
          url: /design/
          weight: 5

params:
    description: "I am Lechen Zhang (张乐晨), a graduate student in Mechanical Engineering at Columbia University. My research intersets are in Robotics, Machine Intellegence and Computer Vision."
    author: Lechen Zhang
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Lechen Zhang
          subtitle: "I am Lechen Zhang(张乐晨), graduate student in Mechanical Engineering at Columbia University. I am currently work as graduate research asistant at Creative Machines Lab, supervised by Prof. Hod Lipson. My research intersets are in Robotics, Machine Intellegence and Computer Vision."
          imageUrl: "pic.png"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Lechen Zhang
          buttons:
            - name: CV
              url: /cv.pdf
            - name: Papers
              url: /papers/
            - name: Projects
              url: /projects/
            - name: Design
              url: /design/
            - name: Tags
              url: /tags/
            - name: Archive
              url: /archive/
    socialIcons:
        - name: Email
          url: mailto:lechen.zhang@columbia.edu
        - name: GitHub
          url: https://github.com/ErvinZzz
        - name: LinkedIn
          url: https://www.linkedin.com/in/lechenzhang/

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Lechen Zhang"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2