baseURL: "https://ErvinZzz.github.io/" 
title: Lechen Zhang
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Home
          url: /
          weight: 1
        - name: CV
          url: cv.pdf
          weight: 2
        - name: Papers
          url: /papers/
          weight: 3
        - name: Projects
          url: /projects/
          weight: 4
        - name: Design
          url: /design/
          weight: 5

params:
    description: "I am Lechen Zhang (张乐晨), a graduate student in Mechanical Engineering at Columbia University. My research intersets are in Robotics, Machine Intellegence and Computer Vision."
    author: Lechen Zhang
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true

    profileMode:
          enabled: true
          title: Lechen Zhang
          subtitle: <br>I am Lechen Zhang, graduate student in Mechanical Engineering at [<u>Columbia University</u>](https://www.columbia.edu/). I am currently work as graduate research asistant at [<u>Creative Machines Lab</u>](https://www.creativemachineslab.com/), supervised by [<u>Hod Lipson</u>](https://scholar.google.com/citations?user=F_Go4V4AAAAJ&hl=en). <br> <br>
          imageUrl: "pic.png"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Lechen Zhang
          buttons:
            - name: CV
              url: /cv.pdf
            # - name: Papers
            #   url: /papers/
            # - name: Projects
            #   url: /projects/
            # - name: Design
            #   url: /design/
            # - name: Tags
            #   url: /tags/
            # - name: Archive
            #   url: /archive/
          updates: |
                  <br><br>
                  <h2 style="color: #4a9eff; font-style: italic;">Recent Updates:</h2>
                  <br>
                  <div style="color: #666666; font-style: italic;">
                    • <a href="https://autourdf.github.io">One paper</a> - Submitted to CVPR 2025 &nbsp;&nbsp;<span style="color: #808080; font-size: 0.9em; border: 1px solid #ddd; padding: 2px 6px; border-radius: 3px;">Nov 2024</span><br>
                    • <a href="https://arxiv.org/abs/2402.03762">One paper</a> - Accepted by IEEE Robotics and Automation Letters (RA-L) &nbsp;&nbsp;<span style="color: #808080; font-size: 0.9em; border: 1px solid #ddd; padding: 2px 6px; border-radius: 3px;">Oct 2024</span><br>
                    • <a href="https://arxiv.org/abs/2405.00698">One paper</a> - Accepted by <a href="https://www.robotmechanisms.org/activities/icra-2024-codesign", style="text-decoration: underline; color: #666666; font-style: italic;" >ICRA 2024 Workshop on Co-design in Robotics</a> as Technical Spotlight Oral &nbsp;&nbsp;<span style="color: #808080; font-size: 0.9em; border: 1px solid #ddd; padding: 2px 6px; border-radius: 3px;">May 2024</span>
                  </div>
                  <br>
    socialIcons:
        - name: Email
          url: mailto:lechen.zhang@columbia.edu
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=8ETNwBsAAAAJ&hl=en
        - name: GitHub
          url: https://github.com/ErvinZzz
        - name: LinkedIn
          url: https://www.linkedin.com/in/lechenzhang/

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Lechen Zhang"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2